# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diary.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diaryWindows(object):
    def setupUi(self, diaryWindows):
        diaryWindows.setObjectName("diaryWindows")
        diaryWindows.resize(766, 571)
        self.centralwidget = QtWidgets.QWidget(diaryWindows)
        self.centralwidget.setObjectName("centralwidget")
        self.notebookBackground = QtWidgets.QLabel(self.centralwidget)
        self.notebookBackground.setGeometry(QtCore.QRect(-240, -60, 1071, 661))
        self.notebookBackground.setText("")
        self.notebookBackground.setPixmap(QtGui.QPixmap("images/notebook.png"))
        self.notebookBackground.setScaledContents(True)
        self.notebookBackground.setObjectName("notebookBackground")
        self.diaryTitle = QtWidgets.QLabel(self.centralwidget)
        self.diaryTitle.setGeometry(QtCore.QRect(130, 30, 241, 31))
        self.diaryTitle.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-radius:0px;")
        self.diaryTitle.setText("")
        self.diaryTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.diaryTitle.setObjectName("diaryTitle")
        self.diaryAuthor = QtWidgets.QLabel(self.centralwidget)
        self.diaryAuthor.setGeometry(QtCore.QRect(490, 400, 231, 21))
        self.diaryAuthor.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"border-radius:0px;")
        self.diaryAuthor.setText("")
        self.diaryAuthor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.diaryAuthor.setObjectName("diaryAuthor")
        self.diaryContent1 = QtWidgets.QLabel(self.centralwidget)
        self.diaryContent1.setGeometry(QtCore.QRect(120, 120, 261, 361))
        self.diaryContent1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.diaryContent1.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"border-radius:0px;")
        self.diaryContent1.setText("")
        self.diaryContent1.setScaledContents(True)
        self.diaryContent1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.diaryContent1.setWordWrap(True)
        self.diaryContent1.setObjectName("diaryContent1")
        self.pic1 = QtWidgets.QLabel(self.centralwidget)
        self.pic1.setGeometry(QtCore.QRect(420, 30, 131, 111))
        self.pic1.setText("")
        self.pic1.setScaledContents(True)
        self.pic1.setObjectName("pic1")
        self.pic2 = QtWidgets.QLabel(self.centralwidget)
        self.pic2.setGeometry(QtCore.QRect(580, 30, 131, 111))
        self.pic2.setText("")
        self.pic2.setScaledContents(True)
        self.pic2.setObjectName("pic2")
        self.pic3 = QtWidgets.QLabel(self.centralwidget)
        self.pic3.setGeometry(QtCore.QRect(420, 190, 131, 111))
        self.pic3.setText("")
        self.pic3.setScaledContents(True)
        self.pic3.setObjectName("pic3")
        self.pic4 = QtWidgets.QLabel(self.centralwidget)
        self.pic4.setGeometry(QtCore.QRect(570, 190, 131, 111))
        self.pic4.setText("")
        self.pic4.setScaledContents(True)
        self.pic4.setObjectName("pic4")
        self.likeButton = QtWidgets.QPushButton(self.centralwidget)
        self.likeButton.setGeometry(QtCore.QRect(650, 440, 61, 51))
        self.likeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/like.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.likeButton.setIcon(icon)
        self.likeButton.setIconSize(QtCore.QSize(50, 50))
        self.likeButton.setObjectName("likeButton")
        diaryWindows.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(diaryWindows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 22))
        self.menubar.setObjectName("menubar")
        diaryWindows.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(diaryWindows)
        self.statusbar.setObjectName("statusbar")
        diaryWindows.setStatusBar(self.statusbar)

        self.retranslateUi(diaryWindows)
        QtCore.QMetaObject.connectSlotsByName(diaryWindows)

    def retranslateUi(self, diaryWindows):
        _translate = QtCore.QCoreApplication.translate
        diaryWindows.setWindowTitle(_translate("diaryWindows", "日记详情"))
