# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diary.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diaryWindows(object):
    def setupUi(self, diaryWindows):
        diaryWindows.setObjectName("diaryWindows")
        diaryWindows.resize(638, 479)
        self.centralwidget = QtWidgets.QWidget(diaryWindows)
        self.centralwidget.setObjectName("centralwidget")
        self.notebookBackground = QtWidgets.QLabel(self.centralwidget)
        self.notebookBackground.setGeometry(QtCore.QRect(-240, -60, 941, 551))
        self.notebookBackground.setText("")
        self.notebookBackground.setPixmap(QtGui.QPixmap("images/notebook.png"))
        self.notebookBackground.setScaledContents(True)
        self.notebookBackground.setObjectName("notebookBackground")
        self.diaryTitle = QtWidgets.QLabel(self.centralwidget)
        self.diaryTitle.setGeometry(QtCore.QRect(140, 40, 101, 21))
        self.diaryTitle.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"border-radius:0px;")
        self.diaryTitle.setText("")
        self.diaryTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.diaryTitle.setObjectName("diaryTitle")
        self.diaryWriter = QtWidgets.QLabel(self.centralwidget)
        self.diaryWriter.setGeometry(QtCore.QRect(370, 350, 231, 21))
        self.diaryWriter.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"border-radius:0px;")
        self.diaryWriter.setText("")
        self.diaryWriter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.diaryWriter.setObjectName("diaryWriter")
        self.diaryContent1 = QtWidgets.QLabel(self.centralwidget)
        self.diaryContent1.setGeometry(QtCore.QRect(70, 90, 241, 301))
        self.diaryContent1.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"border-radius:0px;")
        self.diaryContent1.setText("")
        self.diaryContent1.setAlignment(QtCore.Qt.AlignCenter)
        self.diaryContent1.setObjectName("diaryContent1")
        self.diaryContent2 = QtWidgets.QLabel(self.centralwidget)
        self.diaryContent2.setGeometry(QtCore.QRect(350, 30, 221, 281))
        self.diaryContent2.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"border-radius:0px;")
        self.diaryContent2.setText("")
        self.diaryContent2.setAlignment(QtCore.Qt.AlignCenter)
        self.diaryContent2.setObjectName("diaryContent2")
        diaryWindows.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(diaryWindows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 22))
        self.menubar.setObjectName("menubar")
        diaryWindows.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(diaryWindows)
        self.statusbar.setObjectName("statusbar")
        diaryWindows.setStatusBar(self.statusbar)

        self.retranslateUi(diaryWindows)
        QtCore.QMetaObject.connectSlotsByName(diaryWindows)

    def retranslateUi(self, diaryWindows):
        _translate = QtCore.QCoreApplication.translate
        diaryWindows.setWindowTitle(_translate("diaryWindows", "日记详情"))
