# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_first_windows(object):
    def setupUi(self, first_windows):
        first_windows.setObjectName("first_windows")
        first_windows.resize(563, 393)
        self.label_2 = QtWidgets.QLabel(first_windows)
        self.label_2.setGeometry(QtCore.QRect(120, 20, 311, 211))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/donk.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(first_windows)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 240, 241, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(first_windows)
        QtCore.QMetaObject.connectSlotsByName(first_windows)

    def retranslateUi(self, first_windows):
        _translate = QtCore.QCoreApplication.translate
        first_windows.setWindowTitle(_translate("first_windows", "Dialog"))
        self.label.setText(_translate("first_windows", "东哥带你了解游学推荐系统"))
        self.pushButton.setText(_translate("first_windows", "登录"))
        self.pushButton_2.setText(_translate("first_windows", "注册"))
