# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_first_windows(object):
    def setupUi(self, first_windows):
        first_windows.setObjectName("first_windows")
        first_windows.resize(696, 475)
        self.label_2 = QtWidgets.QLabel(first_windows)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 661, 461))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/background.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(first_windows)
        self.label_3.setGeometry(QtCore.QRect(110, 60, 481, 231))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/th.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(first_windows)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 360, 239, 24))
        self.pushButton_2.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(first_windows)
        self.pushButton.setGeometry(QtCore.QRect(230, 330, 239, 24))
        self.pushButton.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(first_windows)
        QtCore.QMetaObject.connectSlotsByName(first_windows)

    def retranslateUi(self, first_windows):
        _translate = QtCore.QCoreApplication.translate
        first_windows.setWindowTitle(_translate("first_windows", "选择登录/注册界面"))
        self.pushButton_2.setText(_translate("first_windows", "注册"))
        self.pushButton.setText(_translate("first_windows", "登录"))
