# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_windows(object):
    def setupUi(self, main_windows):
        main_windows.setObjectName("main_windows")
        main_windows.resize(860, 586)
        self.centralwidget = QtWidgets.QWidget(main_windows)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(130, 70, 551, 361))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/donk.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        main_windows.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_windows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        main_windows.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_windows)
        self.statusbar.setObjectName("statusbar")
        main_windows.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(main_windows)
        self.toolBar.setObjectName("toolBar")
        main_windows.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionopen = QtWidgets.QAction(main_windows)
        self.actionopen.setObjectName("actionopen")
        self.actionclose = QtWidgets.QAction(main_windows)
        self.actionclose.setObjectName("actionclose")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionclose)
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actionopen)
        self.toolBar.addAction(self.actionclose)

        self.retranslateUi(main_windows)
        QtCore.QMetaObject.connectSlotsByName(main_windows)

    def retranslateUi(self, main_windows):
        _translate = QtCore.QCoreApplication.translate
        main_windows.setWindowTitle(_translate("main_windows", "MainWindow"))
        self.label_2.setText(_translate("main_windows", "我是donk，我将介绍我们组的游学管理系统"))
        self.menu.setTitle(_translate("main_windows", "菜单"))
        self.toolBar.setWindowTitle(_translate("main_windows", "toolBar"))
        self.actionopen.setText(_translate("main_windows", "open"))
        self.actionclose.setText(_translate("main_windows", "close"))
