# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, -30, 831, 591))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/background.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(60, 30, 691, 471))
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"min-width:70px;\n"
"min-height:25px;\n"
"border-top: 2px solid;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"\n"
"color: white;\n"
"\n"
"font:15px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"color: white;\n"
"\n"
"font:17px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"border-bottom: 2px solid;\n"
"\n"
"border-color: #4796f0;\n"
"\n"
"}")
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tempPic = QtWidgets.QLabel(self.tab)
        self.tempPic.setGeometry(QtCore.QRect(10, 0, 651, 351))
        self.tempPic.setText("")
        self.tempPic.setObjectName("tempPic")
        self.tempText = QtWidgets.QLabel(self.tab)
        self.tempText.setGeometry(QtCore.QRect(10, 360, 651, 71))
        self.tempText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"微软雅黑\";")
        self.tempText.setAlignment(QtCore.Qt.AlignCenter)
        self.tempText.setObjectName("tempText")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 691, 451))
        self.tabWidget_3.setStyleSheet("QTabWidget::pane{\n"
"min-width:70px;\n"
"min-height:25px;\n"
"border-top: 2px solid;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"\n"
"color: white;\n"
"\n"
"font:12px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"color: white;\n"
"\n"
"font:13px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"border-bottom: 2px solid;\n"
"\n"
"border-color: #4796f0;\n"
"\n"
"}")
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.diaryTitleList = QtWidgets.QListWidget(self.tab_5)
        self.diaryTitleList.setGeometry(QtCore.QRect(20, 90, 641, 311))
        self.diaryTitleList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.diaryTitleList.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.diaryTitleList.setObjectName("diaryTitleList")
        self.layoutWidget = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 311, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchKeyword = QtWidgets.QLineEdit(self.layoutWidget)
        self.searchKeyword.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"")
        self.searchKeyword.setText("")
        self.searchKeyword.setObjectName("searchKeyword")
        self.horizontalLayout.addWidget(self.searchKeyword)
        self.searchButton = QtWidgets.QPushButton(self.layoutWidget)
        self.searchButton.setStyleSheet("background-color: rgb(38, 40, 72);\n"
"font: 9pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.searchButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon)
        self.searchButton.setAutoExclusive(True)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.searchSelect = QtWidgets.QComboBox(self.layoutWidget)
        self.searchSelect.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.searchSelect.setObjectName("searchSelect")
        self.searchSelect.addItem("")
        self.searchSelect.addItem("")
        self.searchSelect.addItem("")
        self.horizontalLayout_2.addWidget(self.searchSelect)
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.newDiaryTitle = QtWidgets.QLineEdit(self.tab_6)
        self.newDiaryTitle.setGeometry(QtCore.QRect(20, 20, 631, 31))
        self.newDiaryTitle.setAccessibleName("")
        self.newDiaryTitle.setAccessibleDescription("")
        self.newDiaryTitle.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.newDiaryTitle.setObjectName("newDiaryTitle")
        self.newDiaryContent = QtWidgets.QTextEdit(self.tab_6)
        self.newDiaryContent.setGeometry(QtCore.QRect(20, 90, 631, 231))
        self.newDiaryContent.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.newDiaryContent.setObjectName("newDiaryContent")
        self.createButton = QtWidgets.QPushButton(self.tab_6)
        self.createButton.setGeometry(QtCore.QRect(290, 370, 91, 31))
        self.createButton.setStyleSheet("background-color: rgb(38, 40, 72);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"微软雅黑\";")
        self.createButton.setObjectName("createButton")
        self.addImage = QtWidgets.QPushButton(self.tab_6)
        self.addImage.setGeometry(QtCore.QRect(20, 260, 71, 61))
        self.addImage.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/add_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addImage.setIcon(icon1)
        self.addImage.setObjectName("addImage")
        self.picture1 = QtWidgets.QLabel(self.tab_6)
        self.picture1.setGeometry(QtCore.QRect(20, 260, 71, 61))
        self.picture1.setText("")
        self.picture1.setScaledContents(True)
        self.picture1.setAlignment(QtCore.Qt.AlignCenter)
        self.picture1.setObjectName("picture1")
        self.picture2 = QtWidgets.QLabel(self.tab_6)
        self.picture2.setGeometry(QtCore.QRect(91, 260, 71, 61))
        self.picture2.setText("")
        self.picture2.setScaledContents(True)
        self.picture2.setObjectName("picture2")
        self.picture3 = QtWidgets.QLabel(self.tab_6)
        self.picture3.setGeometry(QtCore.QRect(162, 260, 71, 61))
        self.picture3.setText("")
        self.picture3.setScaledContents(True)
        self.picture3.setObjectName("picture3")
        self.picture4 = QtWidgets.QLabel(self.tab_6)
        self.picture4.setGeometry(QtCore.QRect(231, 260, 71, 61))
        self.picture4.setText("")
        self.picture4.setScaledContents(True)
        self.picture4.setObjectName("picture4")
        self.deletePicture = QtWidgets.QPushButton(self.tab_6)
        self.deletePicture.setGeometry(QtCore.QRect(20, 229, 71, 31))
        self.deletePicture.setStyleSheet("background-color: rgb(38, 40, 72);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"微软雅黑\";")
        self.deletePicture.setObjectName("deletePicture")
        self.newDiaryContent.raise_()
        self.picture4.raise_()
        self.picture3.raise_()
        self.picture2.raise_()
        self.picture1.raise_()
        self.newDiaryTitle.raise_()
        self.createButton.raise_()
        self.addImage.raise_()
        self.deletePicture.raise_()
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.school = QtWidgets.QComboBox(self.tab_7)
        self.school.setGeometry(QtCore.QRect(40, 70, 281, 31))
        self.school.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.school.setObjectName("school")
        self.source = QtWidgets.QComboBox(self.tab_7)
        self.source.setGeometry(QtCore.QRect(40, 170, 121, 31))
        self.source.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.source.setObjectName("source")
        self.des = QtWidgets.QComboBox(self.tab_7)
        self.des.setGeometry(QtCore.QRect(40, 270, 121, 31))
        self.des.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.des.setObjectName("des")
        self.searchRoad = QtWidgets.QPushButton(self.tab_7)
        self.searchRoad.setGeometry(QtCore.QRect(40, 340, 101, 31))
        self.searchRoad.setStyleSheet("background-color: rgb(38, 40, 72);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"微软雅黑\";")
        self.searchRoad.setObjectName("searchRoad")
        self.label_2 = QtWidgets.QLabel(self.tab_7)
        self.label_2.setGeometry(QtCore.QRect(40, 35, 211, 21))
        self.label_2.setStyleSheet("background-color: rgb(38, 40, 72);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_7)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 191, 21))
        self.label_3.setStyleSheet("background-color: rgb(38, 40, 72);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_7)
        self.label_4.setGeometry(QtCore.QRect(40, 230, 91, 21))
        self.label_4.setStyleSheet("background-color: rgb(38, 40, 72);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"微软雅黑\";")
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.account = QtWidgets.QTabWidget(self.tab_8)
        self.account.setGeometry(QtCore.QRect(0, 0, 691, 441))
        self.account.setStyleSheet("QTabWidget::pane{\n"
"min-width:70px;\n"
"min-height:25px;\n"
"border-top: 2px solid;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"\n"
"color: white;\n"
"\n"
"font:12px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"color: white;\n"
"\n"
"font:13px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"border-bottom: 2px solid;\n"
"\n"
"border-color: #4796f0;\n"
"\n"
"}")
        self.account.setObjectName("account")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.showMyDiary = QtWidgets.QPushButton(self.tab_3)
        self.showMyDiary.setGeometry(QtCore.QRect(40, 30, 91, 31))
        self.showMyDiary.setStyleSheet("background-color: rgb(38, 40, 72);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"微软雅黑\";")
        self.showMyDiary.setObjectName("showMyDiary")
        self.myDiaryTitleList = QtWidgets.QListWidget(self.tab_3)
        self.myDiaryTitleList.setGeometry(QtCore.QRect(40, 100, 531, 291))
        self.myDiaryTitleList.setObjectName("myDiaryTitleList")
        self.account.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.account.addTab(self.tab_4, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.deleteUserData = QtWidgets.QPushButton(self.tab_9)
        self.deleteUserData.setGeometry(QtCore.QRect(260, 170, 111, 51))
        self.deleteUserData.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.deleteUserData.setObjectName("deleteUserData")
        self.account.addTab(self.tab_9, "")
        self.tabWidget.addTab(self.tab_8, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.account.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "游学推荐系统主界面"))
        self.tempText.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "首页"))
        self.searchKeyword.setPlaceholderText(_translate("MainWindow", "请输入要搜索的关键词"))
        self.searchSelect.setItemText(0, _translate("MainWindow", "标题和内容"))
        self.searchSelect.setItemText(1, _translate("MainWindow", "标题"))
        self.searchSelect.setItemText(2, _translate("MainWindow", "内容"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "日记搜索"))
        self.newDiaryTitle.setPlaceholderText(_translate("MainWindow", "请输入日记标题"))
        self.newDiaryContent.setPlaceholderText(_translate("MainWindow", "请输入日记内容"))
        self.createButton.setText(_translate("MainWindow", "新建日记"))
        self.deletePicture.setText(_translate("MainWindow", "删除图片"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "新建日记"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "游学日记"))
        self.searchRoad.setText(_translate("MainWindow", "搜索推荐路径"))
        self.label_2.setText(_translate("MainWindow", "请输入要搜索的地点"))
        self.label_3.setText(_translate("MainWindow", "请输入起点"))
        self.label_4.setText(_translate("MainWindow", "请输入终点"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "路线导航"))
        self.showMyDiary.setText(_translate("MainWindow", "查看我的日记"))
        self.account.setTabText(self.account.indexOf(self.tab_3), _translate("MainWindow", "我的日记"))
        self.account.setTabText(self.account.indexOf(self.tab_4), _translate("MainWindow", "设置"))
        self.deleteUserData.setText(_translate("MainWindow", "注销账户"))
        self.account.setTabText(self.account.indexOf(self.tab_9), _translate("MainWindow", "账户"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "我的"))
