# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_in_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sign_in_windows(object):
    def setupUi(self, sign_in_windows):
        sign_in_windows.setObjectName("sign_in_windows")
        sign_in_windows.resize(495, 321)
        self.layoutWidget = QtWidgets.QWidget(sign_in_windows)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 70, 301, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color:white;\n"
"font: 9pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color: white;\n"
"font-family: 微软雅黑")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setStyleSheet("size: 9pt;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(sign_in_windows)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 501, 321))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/background.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.autoLogin = QtWidgets.QCheckBox(sign_in_windows)
        self.autoLogin.setGeometry(QtCore.QRect(307, 230, 81, 20))
        self.autoLogin.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.autoLogin.setObjectName("autoLogin")
        self.label_3.raise_()
        self.layoutWidget.raise_()
        self.autoLogin.raise_()
        self.label.setBuddy(self.lineEdit)
        self.label_2.setBuddy(self.lineEdit_2)

        self.retranslateUi(sign_in_windows)
        QtCore.QMetaObject.connectSlotsByName(sign_in_windows)

    def retranslateUi(self, sign_in_windows):
        _translate = QtCore.QCoreApplication.translate
        sign_in_windows.setWindowTitle(_translate("sign_in_windows", "用户登录界面"))
        self.label.setText(_translate("sign_in_windows", "请输入用户名"))
        self.label_2.setText(_translate("sign_in_windows", "输入密码       "))
        self.pushButton.setText(_translate("sign_in_windows", "登录"))
        self.pushButton_2.setText(_translate("sign_in_windows", "取消"))
        self.autoLogin.setText(_translate("sign_in_windows", "自动登录"))
